### PR TITLE
Add MOMO3 log converter supporting Sylphide format

### PR DESCRIPTION
**Pull request by fenrir-naru**
This PR adds a format converter of MOMO3 log, which enables us to analyze the log with tools of [ninja-scan-light](https://github.com/fenrir-naru/ninja-scan-light). The converted format is a.k.a. [Sylphide format](https://github.com/fenrir-naru/ninja-scan-light/wiki/LogFile).

### CODE REVIEW

**Comment by fenrir-naru** [comment]
This is an example post processed result (indirect artifact and not included in this PR). attitude
The definition of axes may differ.

**Comment by ina111** [comment]
Could you tell me definition of axial direction in the figure?
The definition of axis for MOMO(our definition) is below.
https://github.com/istellartech/OpenMOMO/blob/master/MOMO_TF2/others/MOMO2%20%E5%BA%A7%E6%A8%99%E7%B3%BB%E3%83%BB%E9%83%A8%E4%BD%8D%E5%90%8D%E7%A7%B0_%E4%B8%80%E8%88%AC%E5%85%AC%E9%96%8B%E7%94%A8.pdf

**Comment by fenrir-naru** [comment]
@ina111 Thank you for your reviewing and commenting.
I am sorry for your being confused. The graph is an indirect artifact of the PR, and is not included in this PR. Thus, you can merge this PR anytime, because this PR just includes the converter of the low level data consisting of acceleration, angular velocity and FireFly information.
Anyway, I  will check the definition of the attitude graph, and explain the difference later in this thread. Please wait for a while.

**Comment by fenrir-naru** [comment]
I have updated the time history of MOMO3 attitude. The previous graph has error that its initial attitude was wrong. The corrected initial attitude is yaw 90 deg, pitch 0 deg, and roll 180 deg. 
The definition of the attitude angles are same as [the aircraft standard](https://commons.wikimedia.org/wiki/File:MISB_ST_0601.8_-_Yaw,_Pitch_%26_Roll.png), where heading is an alternative name of yawing. The xyz definition is totally followed by the drawing you showed.
Attitude time history
According to the time history, MOMO3 kept the initial attitude to fly higher!

**Comment by ina111** [comment]
Thank you for your great job!

**Pull request merged**
